baseURL = "https://www.uxwriter.life/"
languageCode = "en-us"
title = "Prithvi | UX Writer"
theme="archie-master"
copyright = "© Prithvi"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	featherIconsCDN=true
	subtitle = "👋 Hello. I'm a writer who designs. I strive to create clear, obvious, and humane user experience through microcopies. Currently, I’m at [Whatfix](https://open.spotify.com/playlist/0qakZCBgqW7SFHPWjpHDbj?si=_sytoc1CQxeXUrLYio3iEg), Bangalore focused on creating and managing UX that scale to global products. This website is a home for things I’ve tried and how I tried."

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/prithvi-tharun/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/iprithvitharun"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/iprithvitharun/"

[[params.social]]
name = "Spotify playlist"
icon = "music"
url = "https://open.spotify.com/playlist/0qakZCBgqW7SFHPWjpHDbj?si=_sytoc1CQxeXUrLYio3iEg"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4