baseURL = "https://admiring-dijkstra-8a2945.netlify.app/"
languageCode = "en-us"
title = "Prithvi | UX Writer"
theme="archie-master"
copyright = "© Prithvi"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	featherIconsCDN=true
	subtitle = "I help user interface speak and make products better with language. I’m based in Bangalore, India and build products for the world.  My background combines knowledge from Computer Science Engineering, Human Internet Interaction, and Psychology."

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/prithvi-tharun/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/iprithvitharun"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/iprithvitharun/"

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4